### ISSUE TITLE
Hide `<div class="mw-indicators mw-body-content">` element

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/CustomSubtitle#1]
This empty div prevents rightful text selection. Challenge to WikiLucas !
- [x] Find this element / classes within this current repository.
- [x] Find this element / classes within the LinguaLibre organization
- [x] Propose a solution to hide this element.

```
<div class="mw-indicators mw-body-content">
   <div id="mw-indicator-talk" class="mw-indicator">
   </div>
</div>
```

Note: adapt as necessary. :wink:

**Comment by WikiLucas00** [comment]
On wikis, indicators are icons displayed outside of the main content, usually at the top of a page (see https://www.mediawiki.org/wiki/Help:Page_status_indicators).

As far as I know, on Lingua Libre, indicators are only used in the [Chat room](https://lingualibre.org/wiki/LinguaLibre:Chat_room) and the [Stats page](https://lingualibre.org/wiki/LinguaLibre:Stats). **But** a `<div class="mw-indicators mw-body-content">` element is present on every page that has a blue banner (e.g. [this dummy subpage](https://lingualibre.org/wiki/User:WikiLucas00/Chat_room/topic).
Removing this div in the html when inspecting the element seems to fix the problem (pointer events are possible again on the text).
For the few pages that actually contains an indicator (an icon in the header), a dedicated div with an id and containing an image is contained in the div mentioned above (`<div id="mw-indicator-stats" class="mw-indicator">` inside `<div class="mw-indicators mw-body-content">`). Here, deleting the `<div class="mw-indicators mw-body-content">` is not enough, we have to move the sub-div in the code, right under `<header id="contentHeading">`.
I don't think I have the skills to fix this problem in the php for the moment.

**Comment by hugolpz** [comment]
Good ! Thanks Lucas. We don't have access to the DOM at the moment, and i'am not sure it would be a safe idea to move elements up and down since it could affect and neutralize other css rules we currently aren't aware of.

But ! We can *simulate* this by defining for the elements involved a custom _"vertical altitude"_, via the CSS variable `z-index`. I'am pretty sure it will work, by I have to find the right combinations.

**Comment by hugolpz** [comment]
@WikiLucas00 : I think [this](https://lingualibre.org/index.php?title=MediaWiki:Common.css&diff=prev&oldid=426666) works. 

```
/* CustomSubtitle **************************** */
header#contentHeading { z-index: 0; }
header#contentHeading .mw-indicators { z-index: -1; }
```

**Comment by WikiLucas00** [comment]
@hugolpz Indeed it seems to be working well on LiLi. Thank you!

**Comment by Seb35** [comment]
I guess this issue can be closed given it is now tracked in https://github.com/lingua-libre/BlueLL/issues/5 for the final implementation, isn’t it?

**Comment by hugolpz** [comment]
Yes. Closed.
